# Generated by Django 5.2.1 on 2025-05-31 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.CharField(default=20, max_length=2),
            preserve_default=False,
        ),
    ]
