# Generated by Django 5.2.1 on 2025-05-28 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_status_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
